# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mutopia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentMap',
            fields=[
                ('raw_instrument', models.TextField(primary_key=True, serialize=False)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mutopia.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateTimeField()),
            ],
        ),
    ]
