# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 19:59
from __future__ import unicode_literals

from django.db import migrations, models

MV_CREATE = """
CREATE MATERIALIZED VIEW mutopia_search_view
(id, piece_id, document)
AS SELECT
    p.piece_id,
    p.piece_id,
    (to_tsvector('pg_catalog.simple',
        concat_ws(' ', unaccent(p.title),
            unaccent(c.description),
            unaccent(p.opus),
            p.style_id,
            unaccent(p.raw_instrument),
            unaccent(p.lyricist),
            unaccent(p.source),
            unaccent(m.name),
            p.date_composed,
            unaccent(p.moreinfo),
            v.version)
        )) AS document
    FROM "mutopia_piece" as p
    JOIN "mutopia_lpversion" AS v ON v.id = p.version_id
    JOIN "mutopia_composer" AS c ON c.composer = p.composer_id
    JOIN "mutopia_contributor" AS m ON m.id = p.maintainer_id ;
"""

MV_INDEX = """
CREATE INDEX mutopia_search_index
   ON mutopia_search_view
   USING GIN(document)
"""

class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('document', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'mutopia_search_view',
            },
        ),
        migrations.RunSQL(MV_CREATE),
        migrations.RunSQL(MV_INDEX),
    ]
