# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0002_searchterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmap',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mutopia.Piece'),
        ),
    ]
