# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutopia', '0004_assetmap_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmap',
            name='uses_svg',
            field=models.BooleanField(default=True),
        ),
    ]
